<a href="https://colab.research.google.com/github/M2kishore/Machine-Learning/blob/main/CB_EN_U4CSE19127_Exercise_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise

1. Use famous iris flower dataset from sklearn.datasets to predict flower species using SVM classifier.
2. Measure prediction score by using different Kernal Function
3. Find the best classifer and score for the Kernal Function

# Load the iris flower dataset

In [1]:
# Write your Code Here
# Importing the libraries and dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets,svm

## Understand the dataset
1. iris.DESCR > Complete description of dataset
2. iris.data > Data to learn. Each training set is 4 digit array of features. Total 150 training sets
3. iris.feature_names > Array of all 4 feature ['sepal length (cm)','sepal width cm)','petal length (cm)','petal width (cm)']
4. iris.filename > CSV file name
5. iris.target > The classification label. For every training set there is one classification label(0,1,2). Here 0 for setosa, 1 for versicolor and 2 for virginica
6. iris.target_names > the meaning of the features. Its a array >> ['setosa', 'versicolor', 'virginica']
From above details its clear that our data is 'iris.data' and labels are 'iris.target'

Each training example in iris.data is a array of iris.feature_names lets create a dataframe

# Set the Input and Target Column

In [2]:
#Write your Code Here
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['color'] = iris.target

# Display the shape of the dataset with head and tail portion

In [3]:
#Write your Code Here
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  color
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [4]:
df.tail()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  color
145                6.7               3.0  ...               2.3      2
146                6.3               2.5  ...               1.9      2
147                6.5               3.0  ...               2.0      2
148                6.2               3.4  ...               2.3      2
149                5.9               3.0  ...               1.8      2

[5 rows x 5 columns]

# Preprocessing missing values

In [5]:
#Write your Code Here
df.isnull().sum()
#no null values

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
color                0
dtype: int64

# Preprocessing Duplicate values

In [6]:
#Write your Code Here
df.duplicated().sum()

1

In [7]:
df = df.drop_duplicates()

#  Split the dataset into the Training set and Test set

In [9]:
#Write your Code Here
from sklearn.model_selection import train_test_split
X = df.iloc[:,0:-1].values
Y = df.iloc[:,-1].values
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

# Feature scaling

In [10]:
#Write your Code Here
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

#   Fitting the classifier into the Training set

In [11]:
#Write your Code Here
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_Train, Y_Train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

#   Predicting the test set results

In [12]:
#Write your Code Here
Y_Pred = classifier.predict(X_Test)

#   Display the confusion matrix

In [13]:
#Write your Code Here
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_Test, Y_Pred))

[[12  0  0]
 [ 0 10  0]
 [ 0  1  7]]


#   Display the Classification Report

In [14]:
print(classification_report(Y_Test, Y_Pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      1.00      0.95        10
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



Try by using different Kernal function

Linear kernel

In [17]:
#Write your Code Here
def classReport(ker):
  classifier = SVC(kernel = ker, random_state = 0)
  classifier.fit(X_Train, Y_Train)
  Y_Pred = classifier.predict(X_Test)
  print(confusion_matrix(Y_Test, Y_Pred))
  print(classification_report(Y_Test, Y_Pred))

In [18]:
classReport('linear')

[[12  0  0]
 [ 0 10  0]
 [ 0  1  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      1.00      0.95        10
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



poly kernel

In [20]:
classReport('poly')

[[12  0  0]
 [ 0 10  0]
 [ 0  2  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.83      1.00      0.91        10
           2       1.00      0.75      0.86         8

    accuracy                           0.93        30
   macro avg       0.94      0.92      0.92        30
weighted avg       0.94      0.93      0.93        30



sigmoid kernel

In [21]:
classReport('sigmoid')

[[12  0  0]
 [ 0  9  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.90      0.95        10
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



custom kernel

In [27]:
def xsquare(X,Y):
  return np.dot(X*X,Y.T)

In [28]:
classReport(xsquare)

[[ 3  8  1]
 [10  0  0]
 [ 3  2  3]]
              precision    recall  f1-score   support

           0       0.19      0.25      0.21        12
           1       0.00      0.00      0.00        10
           2       0.75      0.38      0.50         8

    accuracy                           0.20        30
   macro avg       0.31      0.21      0.24        30
weighted avg       0.28      0.20      0.22        30

